export type AddCompanyType = {
  id?: string | string[];
  name: string;
  url: string;
  ceo: string;
  establishedYear: string;
  country: string;
  broker: string;
  platformUse: string[];
  trustPilotReview: string;
  googleReview: string;
  paymentMethod: string;
  payoutMethod: string;
  instrument: string;
  minimumPayoutCondition: string;
  leverage: string;
  commission: string;
  evaluationType: string[];
  step1: string[];
  step2: string[];
  step3: string[];
  instantOrFunded: string[];
  accountSize: number | string;
  actualPrice: number;
  demoAccount: string;
  discountedPrice: string;
  profitSplit: string;
  profitTarget: string;
  drawdownResetType: string;
  dailyDrawdown: number;
  maxDrawdown: number;
  profitToDrawdownRatio: string;
  countriesServing: string[];
  countriesNotServing: string[];
  paymentSettlementDays: string;
  timeLimit: string;
  minimumTradingDays: number;
  newsTrading: string;
  weekendHolding: string;
  expertAdvice: string;
  highFrequencyTrades: string;
  tradeCopier: string;
  firstPayout: string;
  subsequentPayouts: string;
  logo: any;
};
