export type AddCompanyType = {
  id?: string | string[];
  name: string;
  url: string;
  ceo: string;
  establishedYear: string;
  country: string;
  broker: string;
  platformUse: string[];
  trustPilotReview: string;
  googleReview: string;
  paymentMethod: [];
  payoutMethod: [];
  instrument: [];
  minimumPayoutCondition: string;
  leverage: [];
  commission: [];
  evaluationType: string[];
  step1: string;
  step2: string;
  step3: string;
  accountSize: number | string;
  actualPrice: number | string;
  discountedPrice: string;
  profitSplit: string;
  profitTarget: string;
  drawdownResetType: string;
  dailyDrawdown: number | string;
  maxDrawdown: number | string;
  profitToDrawdownRatio: string;
  countriesServing: string[];
  countriesNotServing: string[];
  paymentSettlementDays: string;
  timeLimit: string;
  minimumTradingDays: number | string;
  newsTrading: string;
  weekendHolding: string;
  expertAdvice: string;
  highFrequencyTrades: string;
  tradeCopier: string;
  firstPayout: string;
  subsequentPayouts: string;
  logo: any;
};
